// ui/apps/dashboard/components/Footer.jsx
import "./Footer.scss";
import classNames from "classnames";
import svgGithub from "../../../assets/icon/github.svg?raw";
import svgDiscord from "../../../assets/icon/discord.svg?raw";
import svgTwitter from "../../../assets/icon/twitter.svg?raw";
import svgFacebook from "../../../assets/icon/facebook.svg?raw";
import parse from "html-react-parser";

export default function Footer({ connected }) {
  return (
    <div className={classNames("socials", { connected })}>
      <a href="#" title="GitHub" className="github-logo">
        {parse(svgGithub)}
      </a>
      <a href="#" title="Discord" className="discord-logo">
        {parse(svgDiscord)}
      </a>
      <a href="#" title="Twitter" className="twitter-logo">
        {parse(svgTwitter)}
      </a>
      <a href="#" title="Facebook" className="facebook-logo">
        {parse(svgFacebook)}
      </a>
    </div>
  );
}

// ui/apps/dashboard/components/Footer.svelte
<script>
  import svgGithub from "../../../assets/icon/github.svg";
  import svgDiscord from "../../../assets/icon/discord.svg";
  import svgTwitter from "../../../assets/icon/twitter.svg";
  import svgFacebook from "../../../assets/icon/facebook.svg";
  import { waitForConnected } from "../../../../shared/util.ts";

  let connected = false;

  waitForConnected(() => {
    connected = true;
  });
</script>

<div class="socials" class:connected>
  <a href="#" title="GitHub" class="github-logo">
    {@html svgGithub}
  </a>
  <a href="#" title="Discord" class="discord-logo">
    {@html svgDiscord}
  </a>
  <a href="#" title="Twitter" class="twitter-logo">
    {@html svgTwitter}
  </a>
  <a href="#" title="Facebook" class="facebook-logo">
    {@html svgFacebook}
  </a>
</div>
