// ui/apps/dashboard/components/Network.jsx
import "./Network.scss";
import { useEffect, useState } from "react";
import classNames from "classnames";
import { getNetworkModuleStatus } from "@lumeweb/libkernel";

export default function Network({ module }) {
  let [ready, setReady] = useState(false);
  let [sync, setSync] = useState(null);
  let [peers, setPeers] = useState(0);

  useEffect(() => {
    const destroy = getNetworkModuleStatus((data) => {
      setReady(data.ready);
      setSync(data.sync);
      setPeers(data.peers);
    }, module);

    return () => destroy?.();
  }, [module]);

  return (
    <li className={classNames({ success: ready, loading: !ready })}>
      <div className="network">
        <span
          className={classNames("icon", {
            "icon-success": ready,
            "icon-wait": !ready,
          })}
        />
        Network
      </div>
      {ready ? (
        <div className="status">Synced</div>
      ) : (
        <div className="status">Syncing</div>
      )}
    </li>
  );
}

// ui/apps/dashboard/components/Network.svelte
<script>
  import { onDestroy, onMount } from "svelte";
  import { getNetworkModuleStatus } from "@lumeweb/libkernel";

  export let module;

  let destroy;

  let ready = false;
  let sync = null;
  let peers = 0;

  onMount(() => {
    destroy = getNetworkModuleStatus((data) => {
      ready = data.ready;
      sync = data.sync;
      peers = data.peers;
    }, module);
  });
  onDestroy(() => {
    destroy?.();
  });
</script>

<li class:success={ready}>
  <div class="network">
    <span class="icon" class:icon-success={ready} />
    Network
  </div>
  {#if ready}
    <div class="status">Synced</div>
  {:else}
    <div class="status">Syncing</div>
  {/if}
</li>
